export * from './calculateAvg'
export * from './countByValue'
export * from './shuffleArray'
export * from './transferElements'
export * from './resetInktotal'
export * from './setupHandAndShuffleDeck'
export * from './singASong'
export * from './shiftCharacter'